spring:
  datasource:
    url: jdbc:mysql://localhost:3306/survey_db
    username: root
    password: 2004kfO?

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: survey-app

server:
  port: 8081